/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package atmbank.admin.view.account;

import atmbank.admin.controllers.AccountController;
import atmbank.admin.controllers.CurrencyController;
import atmbank.admin.controllers.CustomerController;
import atmbank.admin.model.Account;
import atmbank.admin.model.Currency;
import atmbank.admin.model.Customer;
import atmbank.admin.security.SystemGetManagement;
import atmbank.admin.security.SystemValidation;
import java.util.Calendar;
import java.util.Date;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Xuan Nguyen
 */
public class JInternalFrameViewAccountAddNew extends javax.swing.JInternalFrame {
    String AccNo,PinNo,fullname,dob,address,phone,CardNo,date,messError,balance,gender;
    float money;
    SystemValidation valid;
    boolean ValidAccNo = false;
    boolean ValidPinNo = false;
    boolean ValidBalance = false;
    boolean ValidFullname = false;
    boolean ValidAddress = false;
    boolean ValidPhone = false;
    AccountController accountController;
    DefaultComboBoxModel comboBoxModel;
    CurrencyController currencyController;
    CustomerController customerController;
    SystemGetManagement systemManagement;
    /**
     * Creates new form JInternalFrameAccountAddNew
     */
    public JInternalFrameViewAccountAddNew() {
        valid = new SystemValidation();
        initComponents();
        systemManagement = new SystemGetManagement();
        systemManagement.getCurrencySymbol(comboBoxModel, cbxCurrency);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        lblTitle = new javax.swing.JLabel();
        txtAccNo = new javax.swing.JTextField();
        lblLaAccNo = new javax.swing.JLabel();
        lblPin = new javax.swing.JLabel();
        txtPIN = new javax.swing.JTextField();
        lblLaStartBalance = new javax.swing.JLabel();
        btnGetAccNo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        rdnBtnMale = new javax.swing.JRadioButton();
        rdnBtnFemale = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAddress = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDate = new com.toedter.calendar.JDateChooser();
        lblIconFullname = new javax.swing.JLabel();
        lblIconAddress = new javax.swing.JLabel();
        lblIconPhone = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        try{
            txtCardNo = new JFormattedTextField(new MaskFormatter("###-###-###"));
            txtPhone = new javax.swing.JTextField();
            lblIconBalance = new javax.swing.JLabel();
            btnGetPinNo = new javax.swing.JButton();
            lblIconAccNo = new javax.swing.JLabel();
            lblIconPin = new javax.swing.JLabel();
            cbxCurrency = new javax.swing.JComboBox();
            txtBalance = new javax.swing.JFormattedTextField();
            jPanel2 = new javax.swing.JPanel();
            btnSubmit = new javax.swing.JButton();
            btnReset = new javax.swing.JButton();
            btnCancel = new javax.swing.JButton();
            lblLaStartBalance1 = new javax.swing.JLabel();

            jFormattedTextField1.setText("jFormattedTextField1");

            setClosable(true);
            setIconifiable(true);
            setTitle("Create New Account");
            setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon22x22_add_new.png"))); // NOI18N

            lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
            lblTitle.setForeground(new java.awt.Color(51, 51, 51));
            lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lblTitle.setText("-----Create New Account -----");

            txtAccNo.setEditable(false);
            txtAccNo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
            txtAccNo.setForeground(new java.awt.Color(51, 51, 51));
            txtAccNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            txtAccNo.setText("0000-0000-0000-0000");
            txtAccNo.setToolTipText("");

            lblLaAccNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            lblLaAccNo.setText("Account No.");

            lblPin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            lblPin.setText("PIN");

            txtPIN.setEditable(false);
            txtPIN.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
            txtPIN.setForeground(new java.awt.Color(51, 51, 51));
            txtPIN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            txtPIN.setText("0000");

            lblLaStartBalance.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            lblLaStartBalance.setText("Start Balance:");

            btnGetAccNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon22x22_refresh.png"))); // NOI18N
            btnGetAccNo.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnGetAccNoActionPerformed(evt);
                }
            });

            jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Information Customer", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 0, 0))); // NOI18N

            jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            jLabel5.setText("Full name:");

            jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            jLabel9.setText("ID Card No.");

            jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            jLabel11.setText("Gender:");

            rdnBtnMale.setBackground(java.awt.Color.white);
            buttonGroup1.add(rdnBtnMale);
            rdnBtnMale.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            rdnBtnMale.setSelected(true);
            rdnBtnMale.setText("Male");

            rdnBtnFemale.setBackground(java.awt.Color.white);
            buttonGroup1.add(rdnBtnFemale);
            rdnBtnFemale.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            rdnBtnFemale.setText("Female");

            jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            jLabel12.setText("DoB:");

            taAddress.setColumns(20);
            taAddress.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
            taAddress.setRows(5);
            taAddress.addFocusListener(new java.awt.event.FocusAdapter() {
                public void focusGained(java.awt.event.FocusEvent evt) {
                    taAddressFocusGained(evt);
                }
            });
            jScrollPane1.setViewportView(taAddress);

            jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            jLabel7.setText("Address:");

            jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            jLabel8.setText("Phone:");

            lblIconFullname.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon24x24_incorrect.png"))); // NOI18N

            lblIconAddress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon24x24_incorrect.png"))); // NOI18N

            lblIconPhone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon24x24_incorrect.png"))); // NOI18N

            txtFullName.addFocusListener(new java.awt.event.FocusAdapter() {
                public void focusGained(java.awt.event.FocusEvent evt) {
                    txtFullNameFocusGained(evt);
                }
            });

        }catch(Exception e){};

        txtPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPhoneFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblIconFullname))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPhone))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(52, 52, 52)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rdnBtnMale)
                                .addGap(18, 18, 18)
                                .addComponent(rdnBtnFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIconPhone)
                            .addComponent(lblIconAddress))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblIconFullname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(rdnBtnMale)
                    .addComponent(rdnBtnFemale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblIconAddress)
                        .addGap(27, 27, 27)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIconPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addGap(21, 21, 21))
        );

        lblIconBalance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon24x24_incorrect.png"))); // NOI18N

        btnGetPinNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon22x22_refresh.png"))); // NOI18N
        btnGetPinNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetPinNoActionPerformed(evt);
            }
        });

        lblIconAccNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon24x24_incorrect.png"))); // NOI18N

        lblIconPin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon24x24_incorrect.png"))); // NOI18N

        cbxCurrency.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtBalance.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        txtBalance.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBalance.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtBalance.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBalanceFocusGained(evt);
            }
        });

        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon22x22_ok.png"))); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel2.add(btnSubmit);

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon22x22_refresh.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel2.add(btnReset);

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon22x22_cancel.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancel);

        lblLaStartBalance1.setText("Note : 12345 or 12,345 ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLaAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPin, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnGetPinNo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblIconPin))
                                    .addComponent(txtAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnGetAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblIconAccNo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLaStartBalance)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLaStartBalance1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbxCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblIconBalance)))))
                        .addContainerGap(60, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtAccNo)
                        .addComponent(lblLaAccNo))
                    .addComponent(btnGetAccNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIconAccNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPIN)
                        .addComponent(lblPin))
                    .addComponent(btnGetPinNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIconPin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblIconBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                        .addComponent(cbxCurrency))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblLaStartBalance)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLaStartBalance1)
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void CheckBalance(){
        ValidBalance = true;
        if(!valid.validateMoney(txtBalance.getText())){
            ValidBalance = false;
        }
        lblIconBalance.setIcon(ValidBalance ? SystemValidation.CORRECT_ICON: SystemValidation.INCORRECT_ICON);
    }
    private void CheckAdress(){
        address = taAddress.getText().trim();
        ValidAddress = true;
        if(address.equals("") || address.length() > 255){
                ValidAddress = false;
        }
        lblIconAddress.setIcon(ValidAddress ? SystemValidation.CORRECT_ICON: SystemValidation.INCORRECT_ICON);
    }
    private void CheckPhone(){
        phone = txtPhone.getText().trim();
        ValidPhone = true;
        if(!valid.validatePhone(phone)){
            ValidPhone = false;
        }
        lblIconPhone.setIcon(ValidPhone ? SystemValidation.CORRECT_ICON: SystemValidation.INCORRECT_ICON);
    }
    private void btnGetAccNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetAccNoActionPerformed
        accountController = new AccountController();
        AccNo = SystemValidation.Convert(new Random().nextInt(9999), 4) + "-" + SystemValidation.Convert(new Random().nextInt(9999), 4)
                + "-" + SystemValidation.Convert(new Random().nextInt(9999), 4) + "-" +SystemValidation.Convert(new Random().nextInt(9999), 4);
        txtAccNo.setText(AccNo);
        ValidAccNo = true;
        if(!accountController.CheckAccNoExists(AccNo)){
            ValidAccNo = false;
        }
        lblIconAccNo.setIcon(ValidAccNo ? SystemValidation.CORRECT_ICON: SystemValidation.INCORRECT_ICON);
        accountController.close();
    }//GEN-LAST:event_btnGetAccNoActionPerformed

    private void btnGetPinNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetPinNoActionPerformed
        PinNo = SystemValidation.Convert(new Random().nextInt(9999), 4);
        txtPIN.setText(PinNo);
        ValidPinNo = true;
        if(PinNo.equals("0000")){
            ValidPinNo = false;
        }
        lblIconPin.setIcon(ValidPinNo ? SystemValidation.CORRECT_ICON: SystemValidation.INCORRECT_ICON);
    }//GEN-LAST:event_btnGetPinNoActionPerformed
    private void CheckFullName(){
    fullname = txtFullName.getText().trim();
    ValidFullname = true;
        if(fullname.equals("")){
            ValidFullname = false;
        }
        lblIconFullname.setIcon(ValidFullname ? SystemValidation.CORRECT_ICON: SystemValidation.INCORRECT_ICON);
    }
    private void GetDataForm(){
    AccNo = txtAccNo.getText();
    PinNo = txtPIN.getText();
    fullname = txtFullName.getText();
    CardNo = txtCardNo.getText();
        if(rdnBtnMale.isSelected()){
            gender = "Male";
        }else{
            gender = "Female";
        }
    //date = txtDate.    
     address = taAddress.getText();
     phone = txtPhone.getText();
     money = SystemValidation.ConvertFloatMoney(txtBalance.getText());
    }
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        accountController = new AccountController();
        Account account = new Account();
        customerController = new CustomerController();
        Customer customer = new Customer();
        Currency currency = new Currency();
        if(!accountController.CheckAccNoExists(txtAccNo.getText())){
           JOptionPane.showMessageDialog(null, "Account already exists ! Please try again", "Error", JOptionPane.ERROR_MESSAGE); 
        }else{
            if(!validForm()){
               JOptionPane.showMessageDialog(null, messError, "Error", JOptionPane.ERROR_MESSAGE);
           }else{
              GetDataForm();
              customer.setCustomerAddress(address);
              customer.setCustomerDoB(txtDate.getDate());
              customer.setCustomerFullName(fullname);
              customer.setCustomerGender(gender);
              customer.setCustomerPhone(phone);
              customer.setCustomerStatus("Enable");
              customer.setIDCardNo(CardNo);
              customerController.AddNewAccount(customer);
              currency.setCurrencyID(cbxCurrency.getSelectedIndex()+1);
              account.setAccBalance(money);
              account.setAccNo(AccNo);
              account.setAccPIN(PinNo);
              account.setAccStatus("Enable");
              account.setCurrencyID(currency);
              account.setCustomerID(customer);
              accountController.AddNewAccount(account);
              JOptionPane.showMessageDialog(null, "Added New Account Successfully", "Add New Account", JOptionPane.INFORMATION_MESSAGE);
              accountController.close();
              customerController.close();
            }   
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtBalanceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBalanceFocusGained
        txtBalance.selectAll();
        txtBalance.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                CheckBalance(); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                CheckBalance(); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                CheckBalance(); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }//GEN-LAST:event_txtBalanceFocusGained

    private void txtFullNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFullNameFocusGained
        txtFullName.selectAll();
        txtFullName.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
               CheckFullName(); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                CheckFullName(); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                CheckFullName(); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }//GEN-LAST:event_txtFullNameFocusGained
    private boolean validForm(){
        customerController = new CustomerController();
        date = String.valueOf(txtDate.getDate());
        CardNo = txtCardNo.getText().trim();
        if( ValidAccNo && ValidPinNo && ValidAddress && ValidBalance && ValidFullname && ValidPhone){
            if(CardNo.length() != 11){
                messError = "Please enter CardNo . Try again";
            }else if(txtDate.getDate().after(new Date())){
                messError = "Date not more than current Date . Please try again";
            }else if(!valid.validateIsDate(date)){
                messError = "Invalid Date .Please select Date";
            }else if(!customerController.CheckIDCardExists(CardNo)){
                messError = "ID CardNo already exists . Please try again";
            }else{
                return true;
            }
        }else{
                messError = "Please check fields";
                return false;
            
        }
        return false;    
    }
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtAccNo.setText("0000-0000-0000-000");
        lblIconAccNo.setIcon(SystemValidation.INCORRECT_ICON);
        lblIconPin.setIcon(SystemValidation.INCORRECT_ICON);
        ValidAccNo = false;
        ValidPinNo = false;
        txtPIN.setText("0000");
        txtBalance.setText("");
        txtFullName.setText("");
        txtCardNo.setText("");
        txtPhone.setText("");
        txtDate.setMaxSelectableDate(Calendar.getInstance().getTime());
        taAddress.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void taAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_taAddressFocusGained
        taAddress.selectAll();
        taAddress.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                CheckAdress(); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                 CheckAdress(); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                 CheckAdress(); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }//GEN-LAST:event_taAddressFocusGained

    private void txtPhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPhoneFocusGained
        txtPhone.selectAll();
        txtPhone.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                CheckPhone(); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                CheckPhone(); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
               CheckPhone(); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }//GEN-LAST:event_txtPhoneFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnGetAccNo;
    private javax.swing.JButton btnGetPinNo;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbxCurrency;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIconAccNo;
    private javax.swing.JLabel lblIconAddress;
    private javax.swing.JLabel lblIconBalance;
    private javax.swing.JLabel lblIconFullname;
    private javax.swing.JLabel lblIconPhone;
    private javax.swing.JLabel lblIconPin;
    private javax.swing.JLabel lblLaAccNo;
    private javax.swing.JLabel lblLaStartBalance;
    private javax.swing.JLabel lblLaStartBalance1;
    private javax.swing.JLabel lblPin;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton rdnBtnFemale;
    private javax.swing.JRadioButton rdnBtnMale;
    private javax.swing.JTextArea taAddress;
    private javax.swing.JTextField txtAccNo;
    private javax.swing.JFormattedTextField txtBalance;
    private javax.swing.JFormattedTextField txtCardNo;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtPIN;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
