/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package atmbank.admin.view.account;

import atmbank.admin.controllers.AccountController;
import atmbank.admin.controllers.CurrencyController;
import atmbank.admin.model.Account;
import atmbank.admin.model.Currency;
import atmbank.admin.model.Customer;
import atmbank.admin.security.SystemGetManagement;
import atmbank.admin.security.SystemValidation;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Xuan Nguyen
 */
public class JInternalFrameViewAddAccountByCardId extends javax.swing.JInternalFrame {
    Customer customer;
    String AccNo,AccPin,balance,card,name;
    float money;
    int IdCustomer;
    SystemValidation valid;
    boolean ValidAccNo = false;
    boolean ValidAccPin = false;
    boolean ValidBalance = false;
    AccountController accountController;
    CurrencyController currencyController;
    DefaultComboBoxModel comboboxModel;
    SystemGetManagement systemManagement;
    Account account;
    Currency currency;
    /**
     * Creates new form JInternalFrameViewAddAccountByCardId
     */
    public JInternalFrameViewAddAccountByCardId(String Card,String name,int IdCustomer) {
        //this.customer = customer;
        this.card = Card;
        this.name = name;
        this.IdCustomer = IdCustomer;
        initComponents();
        lblCustomerCard.setText(card);
        lblCustomerfullname.setText(name);
        systemManagement = new SystemGetManagement();
        systemManagement.getCurrencySymbol(comboboxModel, cbxCurrency);
        valid = new SystemValidation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblLaAccNo1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAddaccount = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblCustomerCard = new javax.swing.JLabel();
        lblLaAccNo2 = new javax.swing.JLabel();
        lblCustomerfullname = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cbxCurrency = new javax.swing.JComboBox();
        txtAccNo = new javax.swing.JTextField();
        lblLaStartBalance = new javax.swing.JLabel();
        lblLaAccNo = new javax.swing.JLabel();
        btnGetAccNo = new javax.swing.JButton();
        btnGetPinNo = new javax.swing.JButton();
        txtBalance = new javax.swing.JFormattedTextField();
        lblPin = new javax.swing.JLabel();
        txtPIN = new javax.swing.JTextField();
        lblIconPin = new javax.swing.JLabel();
        lblIconBalance = new javax.swing.JLabel();
        lblIconAccNo = new javax.swing.JLabel();
        lblLaStartBalance1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Create New Account By Card ID .");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aa.png"))); // NOI18N

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(51, 51, 51));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("--- Create New Account By Card ID ---");

        lblLaAccNo1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLaAccNo1.setText("Customer Card No.");

        btnAddaccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon22x22_ok.png"))); // NOI18N
        btnAddaccount.setText("Add Account");
        btnAddaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddaccountActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddaccount);

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon22x22_refresh.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset);

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon22x22_cancel.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel);

        lblCustomerCard.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblCustomerCard.setForeground(new java.awt.Color(51, 51, 51));
        lblCustomerCard.setText("000-000-000");

        lblLaAccNo2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLaAccNo2.setText("Fullname :");

        lblCustomerfullname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCustomerfullname.setText("..........");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Account", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 51, 51))); // NOI18N
        jPanel2.setToolTipText("");

        cbxCurrency.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtAccNo.setEditable(false);
        txtAccNo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtAccNo.setForeground(new java.awt.Color(51, 51, 51));
        txtAccNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAccNo.setText("0000-0000-0000-0000");
        txtAccNo.setToolTipText("");

        lblLaStartBalance.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLaStartBalance.setText("Start Balance:");

        lblLaAccNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLaAccNo.setText("Account No.");

        btnGetAccNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon22x22_refresh.png"))); // NOI18N
        btnGetAccNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetAccNoActionPerformed(evt);
            }
        });

        btnGetPinNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon22x22_refresh.png"))); // NOI18N
        btnGetPinNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetPinNoActionPerformed(evt);
            }
        });

        txtBalance.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        txtBalance.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBalance.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtBalance.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBalanceFocusGained(evt);
            }
        });

        lblPin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPin.setText("PIN");

        txtPIN.setEditable(false);
        txtPIN.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtPIN.setForeground(new java.awt.Color(51, 51, 51));
        txtPIN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPIN.setText("0000");

        lblIconPin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon24x24_incorrect.png"))); // NOI18N

        lblIconBalance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon24x24_incorrect.png"))); // NOI18N

        lblIconAccNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon24x24_incorrect.png"))); // NOI18N

        lblLaStartBalance1.setText("Note : 12345 or 12,345 ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLaAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPin, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnGetPinNo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblIconPin))
                            .addComponent(txtAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGetAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblIconAccNo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblLaStartBalance)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLaStartBalance1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblIconBalance)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtAccNo)
                        .addComponent(lblLaAccNo))
                    .addComponent(btnGetAccNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIconAccNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPIN)
                        .addComponent(lblPin))
                    .addComponent(btnGetPinNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIconPin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblIconBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbxCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblLaStartBalance)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLaStartBalance1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblLaAccNo1)
                        .addGap(18, 18, 18)
                        .addComponent(lblCustomerCard)
                        .addGap(27, 27, 27)
                        .addComponent(lblLaAccNo2)
                        .addGap(18, 18, 18)
                        .addComponent(lblCustomerfullname, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitle)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLaAccNo1)
                    .addComponent(lblCustomerCard)
                    .addComponent(lblLaAccNo2)
                    .addComponent(lblCustomerfullname))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGetAccNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetAccNoActionPerformed
        accountController = new AccountController();
        AccNo = SystemValidation.Convert(new Random().nextInt(9999), 4) + "-" + SystemValidation.Convert(new Random().nextInt(9999), 4)
                + "-" + SystemValidation.Convert(new Random().nextInt(9999), 4) + "-" + SystemValidation.Convert(new Random().nextInt(9999), 4);
       txtAccNo.setText(AccNo);
       ValidAccNo = true;
       if(!accountController.CheckAccNoExists(AccNo)){
           ValidAccNo = false;
       }
       lblIconAccNo.setIcon(ValidAccNo ?  SystemValidation.CORRECT_ICON : SystemValidation.INCORRECT_ICON);
       accountController.close();
    }//GEN-LAST:event_btnGetAccNoActionPerformed

    private void btnGetPinNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetPinNoActionPerformed
        AccPin = SystemValidation.Convert(new Random().nextInt(9999), 4);
        txtPIN.setText(AccPin);
        ValidAccPin = true;
        if(AccPin.equals("0000")){
            ValidAccPin = false;
        }
        lblIconPin.setIcon(ValidAccPin ?  SystemValidation.CORRECT_ICON : SystemValidation.INCORRECT_ICON);
    }//GEN-LAST:event_btnGetPinNoActionPerformed
    private void CheckBalance(){
        ValidBalance = true;
        if(!valid.validateMoney(txtBalance.getText())){
             ValidBalance = false;
        }
        lblIconBalance.setIcon(ValidBalance ?  SystemValidation.CORRECT_ICON : SystemValidation.INCORRECT_ICON);
    }
    private void getDataFormAdd(){
        AccNo = txtAccNo.getText();
        AccPin = txtPIN.getText();
        money = SystemValidation.ConvertFloatMoney(txtBalance.getText());
    }
    
    
    private void txtBalanceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBalanceFocusGained
        txtBalance.selectAll();
        txtBalance.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
               CheckBalance(); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                CheckBalance(); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                CheckBalance(); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }//GEN-LAST:event_txtBalanceFocusGained

    private void btnAddaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddaccountActionPerformed

        accountController = new AccountController();
        if(!accountController.CheckAccNoExists(txtAccNo.getText())){
            JOptionPane.showMessageDialog(null, "Account ID already exists !! Please try again","Error",JOptionPane.ERROR_MESSAGE);
        }else{
            if(ValidAccNo && ValidAccPin && ValidBalance){
                getDataFormAdd();
                account = new Account();
                currency = new Currency();
                customer = new Customer();
                customer.setCustomerID(IdCustomer);
                currency.setCurrencyID(cbxCurrency.getSelectedIndex()+1);
                account.setAccBalance(money);
                account.setAccNo(AccNo);
                account.setAccPIN(AccPin);
                account.setCustomerID(customer);
                account.setCurrencyID(currency);
                account.setAccStatus("Enable");
                accountController.AddNewAccount(account);
                accountController.close();
                JOptionPane.showMessageDialog(null, "Added account successfully","Add New Account",JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "Please check fields","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAddaccountActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtAccNo.setText("0000-0000-0000-0000");
        lblIconAccNo.setIcon(SystemValidation.INCORRECT_ICON);
        lblIconPin.setIcon(SystemValidation.INCORRECT_ICON);
        ValidAccNo = false;
        ValidAccPin = false;
        txtPIN.setText("0000");
        txtBalance.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
       dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddaccount;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnGetAccNo;
    private javax.swing.JButton btnGetPinNo;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox cbxCurrency;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCustomerCard;
    private javax.swing.JLabel lblCustomerfullname;
    private javax.swing.JLabel lblIconAccNo;
    private javax.swing.JLabel lblIconBalance;
    private javax.swing.JLabel lblIconPin;
    private javax.swing.JLabel lblLaAccNo;
    private javax.swing.JLabel lblLaAccNo1;
    private javax.swing.JLabel lblLaAccNo2;
    private javax.swing.JLabel lblLaStartBalance;
    private javax.swing.JLabel lblLaStartBalance1;
    private javax.swing.JLabel lblPin;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtAccNo;
    private javax.swing.JFormattedTextField txtBalance;
    private javax.swing.JTextField txtPIN;
    // End of variables declaration//GEN-END:variables
}
