/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package atmbank.admin.view.customer;

import atmbank.admin.controllers.AccountController;
import atmbank.admin.controllers.CustomerController;
import atmbank.admin.model.Account;
import atmbank.admin.model.Customer;
import atmbank.admin.model.SystemUser;
import atmbank.admin.security.SystemValidation;
import atmbank.admin.view.account.JInternalFrameViewAccountDetails;
//import atmbank.admin.view.account.JInternalFrameViewAccountDetails;
import atmbank.admin.view.account.JInternalFrameViewAddAccountByCardId;
import atmbank.admin.view.systemframe.SystemAdmin;
import java.text.ParseException;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Xuan Nguyen
 */
public class JInternalFrameViewCustomerManagement extends javax.swing.JInternalFrame {
    CustomerController customerController;
    Customer customer;
     DefaultTableModel tableModel;
     DefaultTableModel tableModel1;
     String gender,CardNo,fullname,status,reason,address,phone,date,messErrors;
     int idCustomer,AccID;
     boolean checkedit = false;
     AccountController accountController;
     Account account;
     SystemAdmin systemAdmin;
     SystemValidation valid;
     SystemUser SystemUser;
    /**
     * Creates new form JInternalFrameViewCustomerManagement
     */
    public JInternalFrameViewCustomerManagement(SystemAdmin systemAdmin,SystemUser SystemUser) {
        this.systemAdmin = systemAdmin;
        this.SystemUser = SystemUser;
        initComponents();
        valid = new SystemValidation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCustomerID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFullname = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        rdMale = new javax.swing.JRadioButton();
        rdFemale = new javax.swing.JRadioButton();
        btnEdit = new javax.swing.JButton();
        txtDate = new com.toedter.calendar.JDateChooser();
        try{
            txtCardID = new JFormattedTextField(new MaskFormatter("###-###-###"));
            jPanel2 = new javax.swing.JPanel();
            btnLoad = new javax.swing.JButton();
            btnSearch = new javax.swing.JButton();
            btnAddNewCustomer = new javax.swing.JButton();
            btnClean = new javax.swing.JButton();
            btnCancel = new javax.swing.JButton();
            btnAddAcc = new javax.swing.JButton();
            btnEnable = new javax.swing.JButton();
            btnDisable = new javax.swing.JButton();
            jPanel3 = new javax.swing.JPanel();
            jScrollPane1 = new javax.swing.JScrollPane();
            tbList = new javax.swing.JTable();
            jPanel5 = new javax.swing.JPanel();
            jScrollPane2 = new javax.swing.JScrollPane();
            tbListAcc = new javax.swing.JTable();

            jRadioButton2.setText("jRadioButton2");

            jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "List Customer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 0, 51))); // NOI18N

            javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
            jPanel4.setLayout(jPanel4Layout);
            jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 0, Short.MAX_VALUE)
            );
            jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 100, Short.MAX_VALUE)
            );

            setClosable(true);
            setIconifiable(true);
            setTitle("Customer Management");
            setToolTipText("");
            setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconcustomer.png"))); // NOI18N

            jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 0, 51))); // NOI18N

            jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            jLabel2.setText("Customer ID.");

            txtCustomerID.setEditable(false);

            jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            jLabel3.setText("Card ID No.");

            jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            jLabel6.setText("Full Name :");

            jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            jLabel1.setText("Birthday :");

            jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            jLabel5.setText("Phone :");

            jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            jLabel7.setText("Address :");

            jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            jLabel8.setText("Gender :");

            buttonGroup1.add(rdMale);
            rdMale.setText("Male");

            buttonGroup1.add(rdFemale);
            rdFemale.setText("Female");

            btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/system_software_update.png"))); // NOI18N
            btnEdit.setText("Update Information");
            btnEdit.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnEditActionPerformed(evt);
                }
            });

        }catch(Exception e){};

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCardID, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPhone)
                    .addComponent(txtDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdMale)
                        .addGap(18, 18, 18)
                        .addComponent(rdFemale)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(rdMale)
                            .addComponent(rdFemale))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEdit))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(txtFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(txtCardID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Action", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 0, 51))); // NOI18N

        btnLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon22x22_refresh.png"))); // NOI18N
        btnLoad.setText("Load / Reload");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon32x32_search.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnAddNewCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon22x22_add_new.png"))); // NOI18N
        btnAddNewCustomer.setText("Add New");
        btnAddNewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewCustomerActionPerformed(evt);
            }
        });

        btnClean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gnome_edit_clear.png"))); // NOI18N
        btnClean.setText("Clean");
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon22x22_cancel.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnAddAcc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_card.png"))); // NOI18N
        btnAddAcc.setText("Add Acc");
        btnAddAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAccActionPerformed(evt);
            }
        });

        btnEnable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon24x24_correct.gif"))); // NOI18N
        btnEnable.setText("Enable Acc");
        btnEnable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnableActionPerformed(evt);
            }
        });

        btnDisable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon24x24_incorrect.png"))); // NOI18N
        btnDisable.setText("Disable Acc");
        btnDisable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLoad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddNewCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClean, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddAcc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEnable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDisable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddNewCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEnable, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDisable, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClean, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "List Customer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 0, 51))); // NOI18N

        tbList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Card ID No.", "Fullname", "Address", "Phone", "Birthday", "Gender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbList);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "List Account Of Customer Select", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 0, 51))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(255, 0, 51));

        tbListAcc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account ID", "Account No.", "Balance", "CurrencySymbol", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbListAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListAccMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbListAcc);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void loadTable(){
        customerController = new CustomerController();
        customer = new Customer();
        Object[] ColumnNames = new String[]{"Customer ID","Card ID No.","Fullname","Address","Phone","Birthday","Gender"};
        tableModel = new DefaultTableModel(ColumnNames,0){
                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return columnIndex == -1;
                }
            };
        List<Customer> list = customerController.ListAllCustomer();
        if(list == null){
            JOptionPane.showMessageDialog(null, "Empty Data");
        }else{
            for(Object obj : list){
                customer = (Customer) obj;
                tableModel.addRow(new Object[]{customer.getCustomerID(),customer.getIDCardNo(),customer.getCustomerFullName(),customer.getCustomerAddress(),customer.getCustomerPhone(),customer.getCustomerDoB(),customer.getCustomerGender()});
            }
            tbList.setModel(tableModel);
        }
    }
    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        loadTable();
        setTableAccNull();
    }//GEN-LAST:event_btnLoadActionPerformed
    private void loadTableAfterSearch(){
       Object[] ColumnNames1 = new String[]{"Customer ID","Card ID No.","Fullname","Address","Phone","Birthday","Gender"};
       tableModel1 = new DefaultTableModel(ColumnNames1,0); 
       gender = rdMale.isSelected() ? "Male":"Female" ;
       tableModel1.addRow(new Object[]{txtCustomerID.getText(),txtCardID.getText(),txtFullname.getText(),txtAddress.getText(),txtPhone.getText(),txtDate.getDate(),gender});
       tbList.setModel(tableModel1);
    }
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try {
            JFormattedTextField jff = new JFormattedTextField(new MaskFormatter("###-###-###"));
            int check = JOptionPane.showConfirmDialog(null, jff,"Enter Card No.",JOptionPane.YES_NO_OPTION);
            if(check == JOptionPane.YES_OPTION){
                if(jff.getText().trim().length() != 11){
                    JOptionPane.showMessageDialog(null, "It not Card No. !! Try again if you want");
                }else{
                    customerController = new CustomerController();
                    customer = new Customer();
                    customer =  customerController.GetCustomerByCardID(jff.getText());
                    if(customer == null){
                        JOptionPane.showMessageDialog(null,"Customer not exists");
                    }else{
                        txtAddress.setText(customer.getCustomerAddress());
                        txtCardID.setText(customer.getIDCardNo());
                        txtCustomerID.setText(String.valueOf(customer.getCustomerID()));
                        txtDate.setDate(customer.getCustomerDoB());
                        txtFullname.setText(customer.getCustomerFullName());
                        txtPhone.setText(customer.getCustomerPhone());
                        if(customer.getCustomerGender().equals("Male")){
                            rdMale.setSelected(true);
                        }else{
                            rdFemale.setSelected(true);
                        }
                        loadTableAfterSearch();
                        customerController.close();
                    }
                }
            }
        } catch (ParseException ex) {
            Logger.getLogger(JInternalFrameViewCustomerManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAddNewCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewCustomerActionPerformed
        JInternalFrameViewAddNewCustomer addnewCustomer = new JInternalFrameViewAddNewCustomer();
        systemAdmin.ShowJInternalFrame(addnewCustomer);
        systemAdmin.SetJIF(addnewCustomer);
    }//GEN-LAST:event_btnAddNewCustomerActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
       txtAddress.setText("");
       txtCardID.setText("");
       txtCustomerID.setText("");
       txtDate.setDate(Calendar.getInstance().getTime());
       txtFullname.setText("");
       txtPhone.setText("");
        setTableCustomerNull();
       setTableAccNull();
    }//GEN-LAST:event_btnCleanActionPerformed
    private void setTableCustomerNull(){
       Object[] ColumnNames1 = new String[]{"Customer ID","Card ID No.","Fullname","Address","Phone","Birthday","Gender"};
        tableModel1 = new DefaultTableModel(ColumnNames1,0);
       tbList.setModel(tableModel1);
    }
    private void setTableAccNull(){
       Object[] ColumnNames = new String[]{"Account ID","Account No.","Balance","CurrencySymbol","Status"};
       tableModel = new DefaultTableModel(ColumnNames,0){
                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return columnIndex == -1;
                }
            };
       tbListAcc.setModel(tableModel);
    }
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAccActionPerformed
        if(!txtCustomerID.getText().equals("")){
            CardNo = txtCardID.getText();
            fullname = txtFullname.getText();
            idCustomer = Integer.parseInt(txtCustomerID.getText());
            JInternalFrameViewAddAccountByCardId addAccountByCard = new JInternalFrameViewAddAccountByCardId(CardNo,fullname,idCustomer);
            systemAdmin.ShowJInternalFrame(addAccountByCard);
            systemAdmin.SetJIF(addAccountByCard);
        }
    }//GEN-LAST:event_btnAddAccActionPerformed

    private void tbListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListMouseClicked
        int RowNo = tbList.getSelectedRow();
        txtCustomerID.setText(tbList.getValueAt(RowNo, 0).toString());
        txtCardID.setText(tbList.getValueAt(RowNo, 1).toString());
        txtFullname.setText(tbList.getValueAt(RowNo, 2).toString());
        txtAddress.setText(tbList.getValueAt(RowNo, 3).toString());
        txtPhone.setText(tbList.getValueAt(RowNo, 4).toString());
        txtDate.setDate((Date) tbList.getValueAt(RowNo, 5));
        gender = tbList.getValueAt(RowNo, 6).toString();
        if(gender.equals("Male")){
            rdMale.setSelected(true);
        }else{
            rdFemale.setSelected(true);
        }
        Object[] ColumnNames = new String[]{"Account ID","Account No.","Balance","CurrencySymbol","Status"};
        tableModel = new DefaultTableModel(ColumnNames,0){
                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return columnIndex == -1;
                }
            };
        accountController = new AccountController();
        account = new Account();
        List<Account> list = accountController.getAccByIDCardNo(tbList.getValueAt(RowNo, 1).toString());
        if(list != null){
            for(Object obj : list){
                account = (Account) obj;
                tableModel.addRow(new Object[]{account.getAccID(),account.getAccNo(),account.getAccBalance(),account.getCurrencyID().getCurrencySymbol(),account.getAccStatus()});
            }
            tbListAcc.setModel(tableModel);
        }else{
            setTableAccNull();
        }
        accountController.close();
        
    }//GEN-LAST:event_tbListMouseClicked

    private void btnEnableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnableActionPerformed
        int RowNo = tbListAcc.getSelectedRow();
        if(RowNo == -1){
            JOptionPane.showMessageDialog(null, "Please select Account !!");
        }else{
              if(tbListAcc.getValueAt(RowNo, 4).toString().equals("Disable")){
                int check  = JOptionPane.showConfirmDialog(null, "Do you want enable account No : "+ tbListAcc.getValueAt(RowNo, 1)+" ,Fullname :" + txtFullname.getText()+" ? ","Enable Account",JOptionPane.YES_NO_OPTION);
                if(check == JOptionPane.YES_OPTION){
                    accountController = new AccountController();
                    accountController.UpdateAccountEnable((int) tbListAcc.getValueAt(RowNo, 0));
                    tbListAcc.setValueAt("Enable", RowNo, 4);
                    JOptionPane.showMessageDialog(null, "Account enable successfully");
                    accountController.close();
                }
            } 
        }
    }//GEN-LAST:event_btnEnableActionPerformed

    private void btnDisableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisableActionPerformed
        int RowNo = tbListAcc.getSelectedRow();
        if(RowNo == -1){
            JOptionPane.showMessageDialog(null, "Please select Account !!");
        }else{
              if(tbListAcc.getValueAt(RowNo, 4).toString().equals("Enable")){
                int check  = JOptionPane.showConfirmDialog(null, "Do you want disable account No : "+ tbListAcc.getValueAt(RowNo, 1)+" ,Fullname : " + txtFullname.getText()+" ? ","Enable Account",JOptionPane.YES_NO_OPTION);
                if(check == JOptionPane.YES_OPTION){
                    reason = JOptionPane.showInputDialog("Reason disable ?");
                    accountController = new AccountController();
                    accountController.UpdateAccountDisable((int) tbListAcc.getValueAt(RowNo, 0),reason);
                    tbListAcc.setValueAt("Disable", RowNo, 4);
                    JOptionPane.showMessageDialog(null, "Account disable successfully");
                    accountController.close();
                }
            } 
        }
    }//GEN-LAST:event_btnDisableActionPerformed
    private void getDataEdit(){
        fullname = txtFullname.getText().trim();
        address = txtAddress.getText().trim();
        date = String.valueOf(txtDate.getDate());
        phone = txtPhone.getText().trim();
        CardNo = txtCardID.getText().trim();
        idCustomer = Integer.parseInt(txtCustomerID.getText());
        gender = rdMale.isSelected() ? "Male":"Female" ;
    }
    private boolean validFormEdit(){
        getDataEdit();
        customerController = new CustomerController();
        if(fullname.equals("") || address.equals("") || date.equals("") || phone.equals("") || (CardNo.length() != 11)){
            messErrors = "Please enter full information"; 
        }else if(txtDate.getDate().after(new Date())){
                messErrors = "Date not more than current Date . Please try again";
        }else if(!valid.validateIsDate(date)){
            messErrors = "Invalid date . Please select Date";
            txtDate.requestFocus();
        }else if(!valid.validatePhone(phone)){
            messErrors = "Invalid phone (ex : 9-12 numbers')";
            txtPhone.requestFocus();
        }else if(!customerController.CheckIDCardExistsEdit(CardNo,idCustomer)){
            messErrors = "ID CardNo already exists . Please try again";
        }else{
            customerController.close();
            return true;
        }
        customerController.close();
        return false;                   
    }
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
       if(!txtCustomerID.getText().equals("")){
            if(!validFormEdit()){
                JOptionPane.showMessageDialog(null, messErrors,"Error",JOptionPane.ERROR_MESSAGE);
            }else{
                int temp = JOptionPane.showConfirmDialog(null, "Do you want update customer Card ID : "+ txtCardID.getText()+" ? ","Update Customer",JOptionPane.YES_NO_CANCEL_OPTION);
                if(temp == JOptionPane.YES_OPTION){
                customer = new Customer();
                customerController = new CustomerController();
                customer.setCustomerAddress(address);
                customer.setCustomerID(idCustomer);
                Date addDate = txtDate.getDate();
                customer.setCustomerDoB(addDate);
                customer.setCustomerFullName(fullname);
                customer.setCustomerGender(gender);
                customer.setCustomerPhone(phone);
                customer.setIDCardNo(CardNo);
                customerController.UpdateCustomer(customer);
                JOptionPane.showMessageDialog(null, "Updated customer successfully","Update Information Customer",JOptionPane.INFORMATION_MESSAGE);
                customerController.close();
                }
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void tbListAccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListAccMouseClicked
       int RowNo = tbListAcc.getSelectedRow();
       if(evt.getClickCount() == 2){
            account = new Account();
            accountController = new AccountController();
            AccID = Integer.parseInt(tbListAcc.getValueAt(RowNo, 0).toString());
            account = accountController.SearchAccountById(AccID);
            accountController.close();
           JInternalFrameViewAccountDetails accountDetails = new JInternalFrameViewAccountDetails(account,systemAdmin,SystemUser);
           systemAdmin.ShowJInternalFrame(accountDetails);
            systemAdmin.SetJIF(accountDetails);
        }
    }//GEN-LAST:event_tbListAccMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAcc;
    private javax.swing.JButton btnAddNewCustomer;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnDisable;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEnable;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnSearch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdFemale;
    private javax.swing.JRadioButton rdMale;
    private javax.swing.JTable tbList;
    private javax.swing.JTable tbListAcc;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JFormattedTextField txtCardID;
    private javax.swing.JTextField txtCustomerID;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextField txtFullname;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
