/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package atmbank.admin.view.systemuser;

import atmbank.admin.view.systemframe.SystemAdmin;
import atmbank.admin.controllers.AdminController;
import atmbank.admin.model.SystemUser;
import atmbank.admin.model.UserGroup;
import atmbank.admin.security.SystemGetManagement;
import atmbank.admin.security.SystemValidation;
import java.awt.event.ItemEvent;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Xuan Nguyen
 */
public class JInternalFrameViewAdminManagement extends javax.swing.JInternalFrame {
    AdminController adminController;
    SystemUser systemUser;
    UserGroup userGroup;
    String status;
    int userId;
    SystemValidation valid;
    DefaultComboBoxModel modelListpermission;
    String fullname,address,phone,email,gender,messErrors,date,username,reason;
    SystemAdmin admin;
    SystemGetManagement systemManagement;
    DefaultTableModel tableModel;
    /**
     * Creates new form JInternalFrameViewAdminManagement
     */
    public JInternalFrameViewAdminManagement(SystemAdmin admin) {
        this.admin = admin;
        initComponents();
        //adminController = new AdminController();
        systemUser = new SystemUser();
        userGroup = new UserGroup();
        valid = new SystemValidation();
        systemManagement = new SystemGetManagement();
        systemManagement.getAllPermission(modelListpermission, cbxPermission);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtFullname = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        lblUsername23 = new javax.swing.JLabel();
        cbxPermission = new javax.swing.JComboBox();
        txtDate = new com.toedter.calendar.JDateChooser();
        rdMale = new javax.swing.JRadioButton();
        rdFemale = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taAdress = new javax.swing.JTextArea();
        txtId = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbList = new javax.swing.JTable();
        btnLoadAllAdmin = new javax.swing.JButton();
        cbbSelect = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnDisable = new javax.swing.JButton();
        btnEnable = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Admin Management");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon24x24_admin_management.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("ID:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Permission :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Fullname :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Username :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Gender :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Address :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("DoB :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Email :");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Phone :");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Status :");

        lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon24x24_correct.gif"))); // NOI18N
        lblStatus.setText("Enable");

        lblUsername23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUsername23.setText(null);

        buttonGroup1.add(rdMale);
        rdMale.setText("Male");

        buttonGroup1.add(rdFemale);
        rdFemale.setText("Female");

        taAdress.setColumns(20);
        taAdress.setRows(5);
        jScrollPane2.setViewportView(taAdress);

        txtId.setEditable(false);

        txtUsername.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2)
                                    .addComponent(cbxPermission, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rdMale)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdFemale))
                                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(txtFullname))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(txtPhone))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtEmail))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUsername23, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername23)
                    .addComponent(jLabel8)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxPermission, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(33, 33, 33)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdMale)
                    .addComponent(rdFemale)
                    .addComponent(jLabel9))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lblStatus))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UserID", "Permission", "Username", "Fullname", "Address", "Gender", "DoB", "EMail", "Phone", "Status", "Check"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbList.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tbList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbList);

        btnLoadAllAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon22x22_refresh.png"))); // NOI18N
        btnLoadAllAdmin.setText("Load / Reload");
        btnLoadAllAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadAllAdminActionPerformed(evt);
            }
        });

        cbbSelect.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbbSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Enable", "Disable" }));
        cbbSelect.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbSelectItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Select :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cbbSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLoadAllAdmin)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLoadAllAdmin)
                    .addComponent(cbbSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon32x32_search.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnClean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon16x16_clean.png"))); // NOI18N
        btnClean.setText("Clean");
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon24x24_add_admin.png"))); // NOI18N
        jButton4.setText("Add New");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnDisable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon24x24_incorrect.png"))); // NOI18N
        btnDisable.setText("Disable");
        btnDisable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisableActionPerformed(evt);
            }
        });

        btnEnable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon24x24_correct.gif"))); // NOI18N
        btnEnable.setText("Enable");
        btnEnable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnableActionPerformed(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon22x22_cancel.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/system_software_update.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClean, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDisable, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnable, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnSearch)
                        .addComponent(btnClean, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDisable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEnable, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void loadTable(){
         adminController = new AdminController();
         systemUser  = new SystemUser();
         Object[] ColumnNames = new String[]{"UserID","Permission","Username","Fullname","Address","Gender","DoB","Email","Phone","Status","ReasonDisable"};
          tableModel = new DefaultTableModel(ColumnNames,0);  
         List<SystemUser> list = adminController.getAllAdmin();
         if(list == null){
              JOptionPane.showMessageDialog(null,"Empty Data");
         }else{     
           for(Object obj : list){
               systemUser = (SystemUser) obj;
               tableModel.addRow(new Object[]{systemUser.getUserID(),systemUser.getGroupId().getGroupName(),systemUser.getUserUsername(),systemUser.getUserFullName(),systemUser.getUserAddress(),systemUser.getUserGender(),systemUser.getUserDoB(),systemUser.getUserEmail(),systemUser.getUserPhone(),systemUser.getUserStatus(),systemUser.getUserStatusReason()});
           }
          tbList.setModel(tableModel);
          adminController.close();
         }
    }
     private void loadTableUserEnable(){  
         adminController = new AdminController();
         systemUser  = new SystemUser();
         List<SystemUser> list = adminController.getAllAdminEnable();
         Object[] ColumnNames = new String[]{"UserID","Permission","Username","Fullname","Address","Gender","DoB","Email","Phone","Status"};
            tableModel = new DefaultTableModel(ColumnNames,0);
         if(list == null){
             tbList.setModel(tableModel); 
         }else{
            for(Object obj : list){
                systemUser = (SystemUser) obj;
                tableModel.addRow(new Object[]{systemUser.getUserID(),systemUser.getGroupId().getGroupName(),systemUser.getUserUsername(),systemUser.getUserFullName(),systemUser.getUserAddress(),systemUser.getUserGender(),systemUser.getUserDoB(),systemUser.getUserEmail(),systemUser.getUserPhone(),systemUser.getUserStatus()});
            }
           tbList.setModel(tableModel);  
           adminController.close();
         }
    } 
      private void loadTableUserDisable(){
          adminController = new AdminController();
          systemUser = new SystemUser();
                    List<SystemUser> list = adminController.getAllAdminDisable();
                    Object[] ColumnNames = new String[]{"UserID","Permission","Username","Fullname","Address","Gender","DoB","Email","Phone","Status","ReasonDisable"};
                    tableModel = new DefaultTableModel(ColumnNames,0);
                    if(list == null){
                        tbList.setModel(tableModel); 
                    }else{
                        for(Object obj : list){
                        systemUser = (SystemUser) obj;
                        tableModel.addRow(new Object[]{systemUser.getUserID(),systemUser.getGroupId().getGroupName(),systemUser.getUserUsername(),systemUser.getUserFullName(),systemUser.getUserAddress(),systemUser.getUserGender(),systemUser.getUserDoB(),systemUser.getUserEmail(),systemUser.getUserPhone(),systemUser.getUserStatus(),systemUser.getUserStatusReason()});
                        }
                        tbList.setModel(tableModel); 
                        adminController.close();
                    }
              
    }     
    private void btnLoadAllAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadAllAdminActionPerformed
        loadTable();
    }//GEN-LAST:event_btnLoadAllAdminActionPerformed

    private void tbListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListMouseClicked
        int RowNo = tbList.getSelectedRow();
        txtId.setText(tbList.getValueAt(RowNo, 0).toString());
        cbxPermission.setSelectedItem(tbList.getValueAt(RowNo, 1).toString());
        txtUsername.setText(tbList.getValueAt(RowNo, 2).toString());
        txtFullname.setText(tbList.getValueAt(RowNo, 3).toString());
        taAdress.setText(tbList.getValueAt(RowNo, 4).toString());
        gender = tbList.getValueAt(RowNo, 5).toString();
        if(gender.equals("Male")){
            rdMale.setSelected(true);
        }else{
            rdFemale.setSelected(true);
        }
        txtDate.setDate((Date) tbList.getValueAt(RowNo, 6));
        txtEmail.setText(tbList.getValueAt(RowNo, 7).toString());
        txtPhone.setText(tbList.getValueAt(RowNo, 8).toString());
        status = tbList.getValueAt(RowNo, 9).toString();
        lblStatus.setIcon(status.equals("Enable") ? SystemValidation.CORRECT_ICON:SystemValidation.INCORRECT_ICON);
        lblStatus.setText(tbList.getValueAt(RowNo, 9).toString());
    }//GEN-LAST:event_tbListMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        adminController = new AdminController();
        String username1 = JOptionPane.showInputDialog("Enter Username :");
        if(!adminController.CheckUserByUsername(username1)){
            JOptionPane.showMessageDialog(null, "Empty Data","Error",JOptionPane.YES_NO_OPTION);
        }else{
            systemUser = adminController.getUserByUsername(username1);
            txtId.setText(String.valueOf(systemUser.getUserID()));
            cbxPermission.setSelectedItem(systemUser.getGroupId().getGroupName());
            txtUsername.setText(systemUser.getUserUsername());
            txtFullname.setText(systemUser.getUserFullName());
            taAdress.setText(systemUser.getUserAddress());
            gender = systemUser.getUserGender();
            if(gender.equals("Male")){
                rdMale.setSelected(true);
            }else{
                rdFemale.setSelected(true);
            }
            txtDate.setDate(systemUser.getUserDoB());
            txtEmail.setText(systemUser.getUserEmail());
            txtPhone.setText(systemUser.getUserPhone());
            lblStatus.setIcon(systemUser.getUserStatus().equals("Enable") ? SystemValidation.CORRECT_ICON:SystemValidation.INCORRECT_ICON);
            lblStatus.setText(systemUser.getUserStatus());
            adminController.close();
        }
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        txtId.setText("");
        txtUsername.setText("");
        txtFullname.setText("");
        taAdress.setText("");
        txtEmail.setText("");
        txtPhone.setText("");
        Object[] ColumnNames = new String[]{"UserID","Permission","Username","Fullname","Address","Gender","DoB","Email","Phone","Status","ReasonDisable"};
        tableModel = new DefaultTableModel(ColumnNames,0);
        tbList.setModel(tableModel);
    }//GEN-LAST:event_btnCleanActionPerformed

    private void btnDisableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisableActionPerformed
         if(!txtId.getText().trim().equals("")){
            if(txtId.getText().equals("1")){
                JOptionPane.showMessageDialog(null, "You can't disable Administrator ID : 1");
            }else{
                if(lblStatus.getText().equals("Enable")){
                    userId = Integer.parseInt(txtId.getText());
                    int ck = JOptionPane.showConfirmDialog(null, "Do you want disable account ID : "+txtId.getText() + " - username : " + txtUsername.getText()+ " ? " , "Disable",JOptionPane.YES_NO_CANCEL_OPTION);
                    if(ck == JOptionPane.YES_OPTION){
                        reason = JOptionPane.showInputDialog("Reason Disable");
                        adminController = new AdminController();
                        adminController.UpdateUserDisable(userId,reason);
                        JOptionPane.showMessageDialog(null, "Disable Account ID : " + txtId.getText() + " successfully");
                        lblStatus.setIcon(SystemValidation.INCORRECT_ICON);
                        lblStatus.setText("Disable");
                        adminController.close();
                    }
                }
            } 
         }
    }//GEN-LAST:event_btnDisableActionPerformed

    private void btnEnableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnableActionPerformed
         if(!txtId.getText().trim().equals("")){   
            if(lblStatus.getText().equals("Disable")){
            userId = Integer.parseInt(txtId.getText());
            int ck = JOptionPane.showConfirmDialog(null, "Do you want enable account ID : "+txtId.getText() + " - username : " + txtUsername.getText()+ " ? " , "Disable",JOptionPane.YES_NO_CANCEL_OPTION);
                if(ck == JOptionPane.YES_OPTION){
                    adminController = new AdminController();
                     adminController.UpdateUserEnable(userId);
                     JOptionPane.showMessageDialog(null, "Enable Account ID : " + txtId.getText() + " successfully");
                    lblStatus.setIcon(SystemValidation.CORRECT_ICON);
                    lblStatus.setText("Enable");
                }
                adminController.close();
            }
         }
    }//GEN-LAST:event_btnEnableActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void cbbSelectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbSelectItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            if(cbbSelect.getSelectedItem().equals("All")){
                loadTable();
            }else if(cbbSelect.getSelectedItem().equals("Enable")){
                loadTableUserEnable();
            }else if(cbbSelect.getSelectedItem().equals("Disable")){
                loadTableUserDisable();
            }
        }
    }//GEN-LAST:event_cbbSelectItemStateChanged
    private void getDataForm(){
        fullname = txtFullname.getText().trim();
        if(rdMale.isSelected()){
            gender = "Male";
        }else{
            gender = "Female";
        }
        date = String.valueOf(txtDate.getDate());
        address = taAdress.getText().trim();
        phone = txtPhone.getText().trim();
        email = txtEmail.getText().trim();
        userId = Integer.parseInt(txtId.getText());
    }
private boolean ValidationFromManagement(){
     adminController = new AdminController();
    getDataForm();
        if(fullname.equals("") || address.equals("") || date.equals("") || phone.equals("") || email.equals("")){
            messErrors = "Please enter full information";
        }else if(txtDate.getDate().after(new Date())){
                messErrors = "Date not more than current Date . Please try again";
            }else if(!valid.validateIsDate(date)){
            messErrors = "Invalid date . Please select Date";
            txtDate.requestFocus();
        }else if(!valid.validatePhone(phone)){
            messErrors = "Invalid phone (ex : 9-12 numbers')";
            txtPhone.requestFocus();
        }else if(!valid.validateEmail(email)){
            messErrors = "Invalid Email Address (ex : bindizz88@gmail.com')";
            txtEmail.requestFocus();
        }else if(adminController.CheckEmailExists(email,userId)){
            messErrors = "Email already exists . Please try again";
            txtEmail.requestFocus();
        }
        else{
            return true;
        }
        return false;
    }
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
         if(!txtId.getText().trim().equals("")){
            if(!ValidationFromManagement()){
                JOptionPane.showMessageDialog(null, messErrors,"Error",JOptionPane.ERROR_MESSAGE);
            }else if(txtId.getText().equals("1")){
                JOptionPane.showMessageDialog(null, "You can't update Account No ID : 1 !! Thank you");
            }else{  
                if(cbxPermission.getSelectedItem().equals("Administrator")){
                    userGroup.setGroupId(1);
                }else{
                    userGroup.setGroupId(2);
                }
                systemUser.setUserID(userId);
                systemUser.setGroupId(userGroup);
                systemUser.setUserFullName(fullname);
                systemUser.setUserAddress(address);
                systemUser.setUserEmail(email);
                systemUser.setUserGender(gender);
                systemUser.setUserPhone(phone);
                Date dateChoose = txtDate.getDate();
                systemUser.setUserDoB(dateChoose);
                adminController = new AdminController();
                adminController.UpdateUserWhere(systemUser);
                JOptionPane.showMessageDialog(null, "Updated Successfully"); 
                adminController.close();
            }
         }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JInternalFrameViewAdminAddNew addNew = new JInternalFrameViewAdminAddNew();
        admin.ShowJInternalFrame(addNew);
    }//GEN-LAST:event_jButton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnDisable;
    private javax.swing.JButton btnEnable;
    private javax.swing.JButton btnLoadAllAdmin;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbbSelect;
    private javax.swing.JComboBox cbxPermission;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblUsername23;
    private javax.swing.JRadioButton rdFemale;
    private javax.swing.JRadioButton rdMale;
    private javax.swing.JTextArea taAdress;
    private javax.swing.JTable tbList;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullname;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
