/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package atmbank.admin.view.systemuser;

import atmbank.admin.controllers.AdminController;
import atmbank.admin.model.SystemUser;
import atmbank.admin.security.SecurityUtils;
import atmbank.admin.security.SystemValidation;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Xuan Nguyen
 */
public class JInternalFrameViewChangePassword extends javax.swing.JInternalFrame {

    SystemUser systemUser;
    SystemValidation valid;
    AdminController adminController;
    /**
     * Creates new form JInternalFrameViewChangePassword
     */
    boolean CheckOldPass = false;
    boolean CheckNewPass1 = false;
    boolean CheckNewPass2 = false;
    String Oldpass, Newpass1, Newpass2;

    public JInternalFrameViewChangePassword(SystemUser systemUser) {
        this.systemUser = systemUser;
        initComponents();
        loadInfor();
        adminController = new AdminController();
    }

    private void loadInfor() {
        lblAdminInfo.setText("ID : " + systemUser.getUserID() + " - " + " Username : " + systemUser.getUserUsername());
    }

    private void CheckOldPass() {
        Oldpass = String.valueOf(txtoldpass.getPassword());
        String hashPassword;
            try {
                hashPassword = SecurityUtils.md5PasswordEncrypt(Oldpass);
            } catch (NoSuchAlgorithmException ex) {
                hashPassword = Oldpass;
                Logger.getLogger(AdminController.class.getName()).log(Level.SEVERE, null, ex);
            }            
        CheckOldPass = hashPassword.equals(systemUser.getUserPassword());
        lblIconOldPass.setIcon(CheckOldPass ? SystemValidation.CORRECT_ICON : SystemValidation.INCORRECT_ICON);
    }

    private void CheckNewPasswordOne() {
        Newpass1 = String.valueOf(txtnewpassone.getPassword());
        Newpass2 = String.valueOf(txtnewpasstwo.getPassword());
        CheckNewPass1 = true;
        if (Newpass2.equals("")) {
            if (Newpass1.length() < 6 || Newpass1.length() > 20) {
                CheckNewPass1 = false;
            }
        } else {
            if (!Newpass1.equals(Newpass2)) {
                CheckNewPass1 = false;
            }
        }
        lbIconNewpass1.setIcon(CheckNewPass1 ? SystemValidation.CORRECT_ICON : SystemValidation.INCORRECT_ICON);
    }

    private void CheckNewPasswordTwo() {
        Newpass1 = String.valueOf(txtnewpassone.getPassword());
        Newpass2 = String.valueOf(txtnewpasstwo.getPassword());
        if (!Newpass2.equals("")) {
            CheckNewPass2 = Newpass2.equals(Newpass1) ? true : false;
            lblNewpass2.setIcon(CheckNewPass2 ? SystemValidation.CORRECT_ICON : SystemValidation.INCORRECT_ICON);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblAdminInfo = new javax.swing.JLabel();
        lblLaOldPass = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bntSave = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblIconOldPass = new javax.swing.JLabel();
        lbIconNewpass1 = new javax.swing.JLabel();
        lblNewpass2 = new javax.swing.JLabel();
        txtoldpass = new javax.swing.JPasswordField();
        txtnewpassone = new javax.swing.JPasswordField();
        txtnewpasstwo = new javax.swing.JPasswordField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Change Administrator Password");
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon32x32_change_password.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Change Password");

        lblAdminInfo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAdminInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdminInfo.setText("..");

        lblLaOldPass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLaOldPass.setText("Old password:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("New password 1:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("New password 2:");

        bntSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon22x22_ok.png"))); // NOI18N
        bntSave.setText("Save");
        bntSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSaveActionPerformed(evt);
            }
        });
        jPanel1.add(bntSave);

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon22x22_refresh.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset);

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon22x22_cancel.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel);

        lblIconOldPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon24x24_incorrect.png"))); // NOI18N

        lbIconNewpass1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon24x24_incorrect.png"))); // NOI18N

        lblNewpass2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon24x24_incorrect.png"))); // NOI18N

        txtoldpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtoldpassActionPerformed(evt);
            }
        });
        txtoldpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtOldPasswordFocusGrained(evt);
            }
        });

        txtnewpassone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNewPasswordOneFocusGrained(evt);
            }
        });

        txtnewpasstwo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNewPasswordTwoFocusGrained(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblAdminInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(18, 18, 18))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblLaOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtoldpass, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                            .addComponent(txtnewpassone)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtnewpasstwo)))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIconOldPass)
                                    .addComponent(lblNewpass2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbIconNewpass1, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAdminInfo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLaOldPass)
                    .addComponent(lblIconOldPass)
                    .addComponent(txtoldpass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lbIconNewpass1)
                    .addComponent(txtnewpassone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(lblNewpass2)
                    .addComponent(txtnewpasstwo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtOldPasswordFocusGrained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOldPasswordFocusGrained
        txtoldpass.selectAll();
        txtoldpass.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                CheckOldPass();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                CheckOldPass();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                CheckOldPass();
            }
        });
    }//GEN-LAST:event_txtOldPasswordFocusGrained

    private void txtNewPasswordOneFocusGrained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewPasswordOneFocusGrained
        txtnewpassone.selectAll();
        txtnewpassone.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                CheckNewPasswordOne(); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                CheckNewPasswordOne(); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                CheckNewPasswordOne(); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }//GEN-LAST:event_txtNewPasswordOneFocusGrained

    private void txtNewPasswordTwoFocusGrained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewPasswordTwoFocusGrained
        txtnewpasstwo.selectAll();
        txtnewpasstwo.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                CheckNewPasswordTwo(); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                CheckNewPasswordTwo(); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                CheckNewPasswordTwo(); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }//GEN-LAST:event_txtNewPasswordTwoFocusGrained

    private void bntSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSaveActionPerformed
        if (CheckOldPass && CheckNewPass1 && CheckNewPass2) {
            String hashPassword;
            try {
                hashPassword = SecurityUtils.md5PasswordEncrypt(Newpass1);
            } catch (NoSuchAlgorithmException ex) {
                hashPassword = Newpass1;
                Logger.getLogger(AdminController.class.getName()).log(Level.SEVERE, null, ex);
            }
            systemUser.setUserPassword(hashPassword);
            adminController.UpdateUser(systemUser);
            adminController.close();
            JOptionPane.showMessageDialog(null, "Updated Password Sucessfully");
        } else {
            JOptionPane.showMessageDialog(null, "Please check fields", "Error", 0);
        }
    }//GEN-LAST:event_bntSaveActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtnewpassone.setText("");
        txtnewpasstwo.setText("");
        txtoldpass.setText("");
        lblNewpass2.setIcon(SystemValidation.INCORRECT_ICON);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtoldpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtoldpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtoldpassActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntSave;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbIconNewpass1;
    private javax.swing.JLabel lblAdminInfo;
    private javax.swing.JLabel lblIconOldPass;
    private javax.swing.JLabel lblLaOldPass;
    private javax.swing.JLabel lblNewpass2;
    private javax.swing.JPasswordField txtnewpassone;
    private javax.swing.JPasswordField txtnewpasstwo;
    private javax.swing.JPasswordField txtoldpass;
    // End of variables declaration//GEN-END:variables
}
